In [1]:
import numpy as np

In [2]:
from Perceptron import Perceptron
from Activation import Activation
from Neuron import Neuron
from Optimizer import Optimizer
from Layer import Layer
from MLP import MLP


1. every `Perceptron` is a `Neuron`

2. every `Neuron` has :
    + a `Loss` function:
        + `Loss.AbE`
        + `Loss.MAbE`
        + `Loss.SqE`
        + `Loss.SqE`
    + an `Activation` function:
        + `Activation.binary`
        + `Activation.linear`
        + `Activation.relu`
        + `Activation.sigmoid`
        + `Activation.tanh`

3. every `Neuron` can `calculate` it's out-put on a given `data-set`

4. every `Perceptron` has:
    + an `Optimizer` function:
        + `Optimizer.grad`

5. every `Perceptron` can perform:
    + `BGD` Batch Gradient Descent
    + `SGD`Stochastic Gradient Discent
    + `mGD` mini Batch Gradient Descent


In [3]:

#+ creating a dataset

x = np.random.uniform(low=0, high=1,size=(1000, 4))
y = np.random.uniform(0,1, 1000)
#+ changing the dataset shape
# data = np.array([(x[i][:] , y[i]) for i in range(1000) ]);
data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);

C:\Users\Arman At\AppData\Local\Temp\ipykernel_10400\4244229438.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);


In [4]:
data[1][1]

0.4962921089361112

In [5]:
np.size(data[:,1])

1000

In [6]:
data[:,0]

array([array([0.41473001, 0.55836441, 0.60376557, 0.84924284]),
       array([0.37730062, 0.89955686, 0.67033124, 0.84682197]),
       array([0.73807802, 0.84024917, 0.05306472, 0.58177852]),
       array([0.50337253, 0.0091616 , 0.10132296, 0.79334497]),
       array([0.30107147, 0.9424876 , 0.97772104, 0.21559499]),
       array([0.58758223, 0.53552317, 0.38577265, 0.30529304]),
       array([0.47268196, 0.83852002, 0.35807513, 0.70012908]),
       array([0.8609171 , 0.33681784, 0.51236237, 0.76103143]),
       array([0.83641821, 0.83283288, 0.05855665, 0.31851315]),
       array([0.3322181 , 0.21801549, 0.56567939, 0.82631407]),
       array([0.09975027, 0.30775505, 0.37954506, 0.17489112]),
       array([0.70746407, 0.51452742, 0.35214145, 0.8328257 ]),
       array([0.00763122, 0.75289312, 0.21050092, 0.16350991]),
       array([0.98256625, 0.56593893, 0.34629215, 0.74397392]),
       array([0.81573827, 0.75876735, 0.57185129, 0.20250877]),
       array([0.8098745 , 0.02425868, 0.

In [7]:
data[2][1]

0.5295887765117829

In [8]:
my_act = Activation()

# print(my_act.sigmoid(10))
my_neuron = Neuron(num_features=4,act_func= my_act.sigmoid)


In [9]:
my_act.tanh(data[1][0])

array([0.36036091, 0.71608203, 0.58519773, 0.68940555])

In [10]:
my_neuron.Loss.AbE(data=data[1])

0.9687365628300917

In [11]:
my_perceptron = Perceptron(num_featuress=4, act_func= my_act.sigmoid)
# my_loss = Loss(my_perceptron)
print(my_perceptron.weights)

[0.44714078 0.2022306  0.20770612 0.45760587]


In [12]:
my_perceptron.Loss.MAbE(data=data)

0.0010506306243457085

In [13]:
my_perceptron.BGD(data=data,alpha= 10, epoch=1000)


array([0.36566816, 0.12075798, 0.1262335 , 0.37613326])

In [14]:
my_perceptron.Loss.MAbE(data=data)

0.00033037312047961453

In [15]:
data[10][0]

array([0.09975027, 0.30775505, 0.37954506, 0.17489112])

In [16]:
my_perceptron.Loss.MAbE(data=data)

0.00033037312047961453

In [17]:
my_perceptron.SGD(data=data, lss_fun='AbE')

array([0.7710928 , 0.52618262, 0.53165814, 0.78155789])

In [18]:
my_perceptron.Loss.MAbE(data=data)


0.0039145239057297755

In [19]:
data[0]

array([array([0.41473001, 0.55836441, 0.60376557, 0.84924284]),
       0.6048336624214905], dtype=object)

In [20]:
l1 = Layer(n_neuron=5, num_features= 4, act_func=my_act.sigmoid)
for i in range(10):
    print(l1.calculate(data=data[i][0]))

[(1.6046015195221912, 0.8326605287579217), (1.331916414746398, 0.7911574555724827), (1.2497430056317271, 0.7772553710489912), (1.544486484660466, 0.8241159818514272), (0.9513971155021965, 0.7213960624188572)]
[(1.9415312937369782, 0.8745202757248938), (1.3915677077140503, 0.8008424008214792), (1.3247416617293801, 0.7899695137504642), (1.783604599676448, 0.8561413905126012), (1.2020838520119763, 0.7688952817348241)]
[(1.2254419837502533, 0.7730198193022659), (1.0615770158346394, 0.7429917997169947), (1.366616394923796, 0.7968329311625624), (1.2972687551470625, 0.7853749601591618), (0.8209456218727528, 0.6944370325081496)]
[(0.6801459719165561, 0.6637712760449809), (0.9385809478439985, 0.7188129263929565), (1.0977847103001428, 0.7498447969541934), (0.9340211420271531, 0.7178903754510146), (0.2882926620534139, 0.5715780970499225)]
[(1.825875921306856, 0.8612696983361479), (1.1798339722914932, 0.7649179502267799), (0.7335326881791451, 0.6755800174507164), (1.3163184537797528, 0.78856854106

In [21]:
my_model = MLP()
my_model.Layers

[]

In [22]:
my_model.add(n_features=4,n_neuron=10,act_func='sigmoid')
my_model.add(n_features=4,n_neuron=5,act_func='sigmoid')
my_model.add(n_features=4,n_neuron=4,act_func='sigmoid')


In [24]:
my_model.Layers[0].calculate(data=data[4][0])


[(1.4255387880985597, 0.8062052554232506),
 (1.4551852961344822, 0.8107951736030498),
 (0.8909095337779424, 0.709077832742442),
 (1.4759692546099665, 0.813962988317003),
 (1.5542809383275196, 0.8255311725625109),
 (1.3168390243612909, 0.7886553218210289),
 (1.7021178959799954, 0.8458111419231321),
 (1.694178409509211, 0.8447728713579955),
 (1.2646753234903683, 0.7798298886563539),
 (1.7721539785627936, 0.8547253348556612)]