In [2]:
import numpy as np

In [3]:
from Perceptron import Perceptron
from Activation import Activation
from Neuron import Neuron
from Optimizer import Optimizer



1. every `Perceptron` is a `Neuron`

2. every `Neuron` has :
    + a `Loss` function:
        + `Loss.AbE`
        + `Loss.MAbE`
        + `Loss.SqE`
        + `Loss.SqE`
    + an `Activation` function:
        + `Activation.binary`
        + `Activation.linear`
        + `Activation.relu`
        + `Activation.sigmoid`
        + `Activation.tanh`

3. every `Neuron` can `calculate` it's out-put on a given `data-set`

4. every `Perceptron` has:
    + an `Optimizer` function:
        + `Optimizer.grad`

5. every `Perceptron` can perform:
    + `BGD` Batch Gradient Descent
    + `SGD`Stochastic Gradient Discent
    + `mGD` mini Batch Gradient Descent


In [24]:
from typing import Literal, get_args
from Loss import _Losses
class Layer:
    def __init__(self, n_neuron: int, num_features: int ,**kwargs) -> None:
        self.num_features = num_features
        self.weightss = kwargs.get('weights', np.random.uniform(0,1, size=(n_neuron,num_features)))
        self.bioses = kwargs.get('bios', np.zeros(n_neuron) )
        self.n_neuron = n_neuron
        self.Losses = []
        act_tmp = kwargs.get('act_func', None)
        if act_tmp:
            self.active = act_tmp
        else:
            act_tmp = Activation()
            self.active = act_tmp.linear
        self.perceptrons = []
        for i in range(n_neuron):
            p = Perceptron(num_featuress=num_features, weights =self.weightss[i], act_func = self.active, bios=self.bioses[i])
            self.perceptrons.append(p)

    def calculate(self, data):
        self.outputs = []
        for i in range(self.n_neuron):
            output = self.perceptrons[i].calculate(data)
            self.outputs.append(output)
        
        return self.outputs
    # TODO: `loss` function should compute loss of the layer on a given set of data and a given loss_function from the class Loss
    
    def loss(data: np.array, lss_func):
        pass
        # lss_func = lss_func
        # for percept in self.perceptrons:
        #     l = percept.Loss
    def BGD(self, data: np.array, alpha: float = 0.1,delta=0.001, epoch=4, lss_fun='MAbE'):
        """ 
        batch gradient descent

        data: X |Y 
        last element of each record is the label of that record
        """
        options = get_args(_Losses)
        assert lss_fun in options, f" '{lss_fun}' is not in {options}"
        
        for perceptron in self.perceptrons:
            new_weights = perceptron.weights
            grad = perceptron.optimize.grad
            
            tmp_neuron = Neuron(num_features=perceptron.num_features, 
                                active=perceptron.active,
                                weights= new_weights,
                                bios= perceptron.bios)
            for i in range(epoch):
                tmp_neuron.weights = new_weights
                new_weights -= alpha * grad(nueron= tmp_neuron,
                                            loss_fun= lss_fun,
                                            data= data,
                                            delta=delta)
            perceptron.weights = new_weights


In [ ]:
class MLP:
    def __init__(self) -> None:
        pass

In [5]:

#+ creating a dataset

x = np.random.uniform(low=0, high=1,size=(1000, 4))
y = np.random.uniform(0,1, 1000)
#+ changing the dataset shape
# data = np.array([(x[i][:] , y[i]) for i in range(1000) ]);
data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);

C:\Users\Arman At\AppData\Local\Temp\ipykernel_16972\4244229438.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);


In [6]:
data[1][1]

0.7249580925681886

In [7]:
np.size(data[:,1])

1000

In [ ]:
data[2][1]

0.2586902598184616

In [ ]:
my_act = Activation()

# print(my_act.sigmoid(10))
my_neuron = Neuron(num_features=4,act_func= my_act.sigmoid)


In [ ]:
my_neuron.Loss.AbE(data=data[1])

0.35069499443787056

In [ ]:
my_perceptron = Perceptron(num_featuress=4, act_func= my_act.tanh)
# my_loss = Loss(my_perceptron)
print(my_perceptron.weights)

[0.74894629 0.57861209 0.64655495 0.63651734]


In [ ]:
my_perceptron.Loss.MAbE(data=data)

0.0012417738552928203

In [ ]:
my_perceptron.BGD(data=data,alpha= 10, epoch=1000)


array([0.36875943, 0.19842523, 0.26636809, 0.25633048])

In [ ]:
my_perceptron.Loss.MAbE(data=data)

0.0012347672592972292

In [ ]:
data[10][0]

array([0.34601189, 0.69584514, 0.14833455, 0.26978107])

In [ ]:
my_perceptron.Loss.MAbE(data=data)

0.0012347672592972292

In [ ]:
my_perceptron.SGD(data=data, lss_fun='AbE')

305


array([0.36875943, 0.19842523, 0.26636809, 0.25633048])

In [ ]:
my_perceptron.Loss.MAbE(data=data)


0.0012347672592972162

In [23]:
l1 = Layer(n_neuron=10, num_features= 4)
l1.calculate(data=data)

[(array([array([0.99943978, 1.38402481, 0.98480715, 0.97608682]),
         1.2049823941921796], dtype=object),
  array([array([0.99943978, 1.38402481, 0.98480715, 0.97608682]),
         1.2049823941921796], dtype=object)),
 (array([array([0.59059842, 1.42327117, 1.20695198, 1.46868863]),
         1.786944815855506], dtype=object),
  array([array([0.59059842, 1.42327117, 1.20695198, 1.46868863]),
         1.786944815855506], dtype=object)),
 (array([array([0.39375089, 0.80382041, 0.64689887, 0.84825885]),
         0.8330715130481288], dtype=object),
  array([array([0.39375089, 0.80382041, 0.64689887, 0.84825885]),
         0.8330715130481288], dtype=object)),
 (array([array([0.85998611, 1.09429315, 0.8331012 , 0.94821812]),
         1.0032261059024743], dtype=object),
  array([array([0.85998611, 1.09429315, 0.8331012 , 0.94821812]),
         1.0032261059024743], dtype=object)),
 (array([array([0.97103718, 1.60242683, 1.26918104, 1.50704587]),
         1.667347937925288], dtype=object),
