In [1]:
import numpy as np

In [2]:
from Perceptron import Perceptron
from Activation import Activation
from Neuron import Neuron
from Optimizer import Optimizer
from Layer import Layer
from MLP import MLP


1. every `Perceptron` is a `Neuron`

2. every `Neuron` has :
    + a `Loss` function:
        + `Loss.AbE`
        + `Loss.MAbE`
        + `Loss.SqE`
        + `Loss.SqE`
    + an `Activation` function:
        + `Activation.binary`
        + `Activation.linear`
        + `Activation.relu`
        + `Activation.sigmoid`
        + `Activation.tanh`

3. every `Neuron` can `calculate` it's out-put on a given `data-set`

4. every `Perceptron` has:
    + an `Optimizer` function:
        + `Optimizer.grad`

5. every `Perceptron` can perform:
    + `BGD` Batch Gradient Descent
    + `SGD`Stochastic Gradient Discent
    + `mGD` mini Batch Gradient Descent


In [3]:

#+ creating a dataset

x = np.random.uniform(low=0, high=1,size=(1000, 4))
y = np.random.uniform(0,1, 1000)
#+ changing the dataset shape
# data = np.array([(x[i][:] , y[i]) for i in range(1000) ]);
data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);

C:\Users\Arman At\AppData\Local\Temp\ipykernel_6080\4244229438.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);


In [4]:
data[1][1]

0.07358118363367483

In [5]:
np.size(data[:,1])

1000

In [6]:
data[:,0]

array([array([0.03184618, 0.55447649, 0.32147131, 0.84529912]),
       array([0.65431355, 0.91582698, 0.34212304, 0.53347925]),
       array([0.38803583, 0.78854892, 0.62005743, 0.03544101]),
       array([0.12328844, 0.65353924, 0.40094005, 0.06604963]),
       array([0.78160572, 0.97925667, 0.28351276, 0.44181277]),
       array([0.63202194, 0.71734696, 0.78556376, 0.83528158]),
       array([0.40331731, 0.2010654 , 0.8125912 , 0.54821988]),
       array([0.44045953, 0.64160123, 0.88179618, 0.61093689]),
       array([0.85255162, 0.38486334, 0.68992276, 0.47341023]),
       array([0.46343654, 0.84433824, 0.55158051, 0.14936721]),
       array([0.31650382, 0.49618176, 0.13459014, 0.92370794]),
       array([0.31102965, 0.7697329 , 0.32944631, 0.87719513]),
       array([0.85857112, 0.50419792, 0.95982888, 0.83256667]),
       array([0.0150827 , 0.21913991, 0.14962018, 0.24010928]),
       array([0.69402919, 0.00558562, 0.5278023 , 0.95513648]),
       array([0.65136901, 0.49145302, 0.

In [7]:
data[2][1]

0.3689673151251103

In [8]:
my_act = Activation()

# print(my_act.sigmoid(10))
my_neuron = Neuron(num_features=4,act_func= my_act.sigmoid)


In [9]:
my_act.tanh(data[1][0])

array([0.57456666, 0.72391729, 0.32937144, 0.48803615])

In [10]:
my_neuron.Loss.AbE(data=data[1])

1.3474604786669002

In [11]:
my_perceptron = Perceptron(num_featuress=4, act_func= my_act.sigmoid)
# my_loss = Loss(my_perceptron)
print(my_perceptron.weights)

[0.71113243 0.51180947 0.45759237 0.61160078]


In [12]:
my_perceptron.Loss.MAbE(data=data)

0.0027597930309736897

In [13]:
my_perceptron.BGD(data=data,alpha= 10, epoch=1000)


array([0.34881767, 0.1494947 , 0.0952776 , 0.24928602])

In [14]:
my_perceptron.Loss.MAbE(data=data)

0.0007902550209996776

In [15]:
data[10][0]

array([0.31650382, 0.49618176, 0.13459014, 0.92370794])

In [16]:
my_perceptron.Loss.MAbE(data=data)

0.0007902550209996776

In [17]:
my_perceptron.SGD(data=data, lss_fun='AbE')

array([0.34881767, 0.1494947 , 0.0952776 , 0.24928602])

In [18]:
my_perceptron.Loss.MAbE(data=data)


0.000790255020999651

In [19]:
data[0]

array([array([0.03184618, 0.55447649, 0.32147131, 0.84529912]),
       0.3373924489074661], dtype=object)

In [20]:
l1 = Layer(n_neuron=5, num_features= 4, act_func=my_act.sigmoid)
for i in range(10):
    print(l1.calculate(data=data[i][0]))

[(1.0129008311127286, 0.7335874626835642), (0.8894617721230529, 0.7087790887398442), (0.8779601340159826, 0.7063993324788177), (0.37652296230159904, 0.5930342107506639), (0.7330324591596645, 0.6754703717994861)]
[(1.2506759586135896, 0.7774168509131233), (1.3637068171379387, 0.7963614921712473), (1.6193299990686618, 0.8347027077648218), (0.5960881135846073, 0.6447608191650547), (1.212398468893518, 0.7707230553295471)]
[(0.9931306005981878, 0.7297058309262391), (1.096344533366051, 0.7495745548618257), (1.244034556003796, 0.7762655062826038), (0.6171756169779328, 0.6495759145244917), (0.6424319317311966, 0.6553029950091885)]
[(0.6954080640092818, 0.6671688957501273), (0.6992799202342168, 0.6680281018837468), (0.8508702756562099, 0.7007496707821373), (0.3717068202662227, 0.5918713419117851), (0.3449010425769606, 0.5853805513602892)]
[(1.233883164032299, 0.7744974960573078), (1.396583335008989, 0.8016411556020044), (1.733445799622797, 0.8498526453249934), (0.594595092476655, 0.644418777320

In [21]:
my_model = MLP()
my_model.Layers

[]

In [22]:
my_model.add(n_features=4,n_neuron=10,act_func='sigmoid')
my_model.add(n_features=10,n_neuron=5,act_func='sigmoid')
my_model.add(n_features=5,n_neuron=4,act_func='sigmoid')


In [23]:
[elem[0] for elem in my_model.Layers[0].calculate(data=data[4][0])]


[1.1616467880374937,
 0.9434736943622508,
 0.8191509543855375,
 1.7382449197425593,
 0.8401352387216153,
 0.9401780445611898,
 0.5657659125385356,
 1.3329691332128621,
 0.4192549272392454,
 1.1954615609220032]

In [24]:
my_model.calculate(features=data[4][0])

[11.102099992475331,
 13.692021369916556,
 10.709479915617127,
 11.730491350424801]