In [1]:
import numpy as np

In [32]:
from Perceptron import Perceptron
from Loss import Loss
Loss.AbE
Loss.MAbE
Loss.SqE
Loss.SqE


1. every `Perceptron` is a `Neuron`

2. every `Neuron` has :
    + a `Loss` function:
        + `Loss.AbE`
        + `Loss.MAbE`
        + `Loss.SqE`
        + `Loss.SqE`
    + an `Activation` function:
        + `Activation.binary`
        + `Activation.linear`
        + `Activation.relu`
        + `Activation.sigmoid`
        + `Activation.tanh`

3. every `Neuron` can `calculate` it's out-put on a given `data-set`

4. every `Perceptron` has:
    + an `Optimizer` function:
        + `Optimizer.grad`

5. every `Perceptron` can perform:
    + `BGD` Batch Gradient Descent
    + `SGD`Stochastic Gradient Discent
    + `mGD` mini Batch Gradient Descent


In [4]:
class Layer:
    def __init__(self) -> None:
        pass
    

In [5]:
class MLP:
    def __init__(self) -> None:
        pass

In [96]:

#+ creating a dataset

x = np.random.uniform(low=0, high=1,size=(1000, 4))
y = np.random.uniform(0,1, 1000)
#+ changing the dataset shape
# data = np.array([(x[i][:] , y[i]) for i in range(1000) ]);
data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);

C:\Users\Arman At\AppData\Local\Temp\ipykernel_24572\4244229438.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array([(x[i,:] , y[i]) for i in range(1000) ]);


In [101]:
data[1][1]

0.7359169045938435

In [23]:
np.size(data[:,1])

1000

In [39]:
data[2][1]

0.2586902598184616

In [151]:
from Activation import Activation
from Neuron import Neuron

In [152]:
my_act = Activation()

# print(my_act.sigmoid(10))
my_neuron = Neuron(num_features=4,act_func= my_act.sigmoid)


In [153]:
my_neuron.Loss.AbE(data=data[1])

0.35069499443787056

In [111]:
my_perceptron = Perceptron(num_featuress=4, act_func= my_act.tanh)
# my_loss = Loss(my_perceptron)
print(my_perceptron.weights)

[0.74894629 0.57861209 0.64655495 0.63651734]


In [143]:
my_perceptron.Loss.MAbE(data=data)

0.0012417738552928203

In [144]:
my_perceptron.BGD(data=data,alpha= 10, epoch=1000)


array([0.36875943, 0.19842523, 0.26636809, 0.25633048])

In [145]:
my_perceptron.Loss.MAbE(data=data)

0.0012347672592972292

In [146]:
data[10][0]

array([0.34601189, 0.69584514, 0.14833455, 0.26978107])

In [147]:
my_perceptron.Loss.MAbE(data=data)

0.0012347672592972292

In [148]:
my_perceptron.SGD(data=data, lss_fun='AbE')

305


array([0.36875943, 0.19842523, 0.26636809, 0.25633048])

In [149]:
my_perceptron.Loss.MAbE(data=data)


0.0012347672592972162